//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHDepositDetail
    {
        public int ACHDepositId { get; set; }
        public string ACHDepositResourceId { get; set; }
        public byte[] TransactionID { get; set; }
        public string Amount { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
