//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckDetail
    {
        public CheckDetail()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int CheckId { get; set; }
        public int UserId { get; set; }
        public string Payee { get; set; }
        public string NameOnCheck { get; set; }
        public string AddressOnCheck { get; set; }
        public string CityOnCheck { get; set; }
        public string StateOnCheck { get; set; }
        public string ZipOnCheck { get; set; }
        public System.DateTime DateOnCheck { get; set; }
        public decimal Amount { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankCity { get; set; }
        public string BankState { get; set; }
        public string BankZip { get; set; }
        public string CheckNumber { get; set; }
        public string RountingNumber { get; set; }
        public string AccountNumber { get; set; }
        public string CheckMemo { get; set; }
        public string Comments { get; set; }
        public System.DateTime InsertedOn { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
