//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    
    public partial class CustomerDetail
    {
        public int CustomerId { get; set; }
        public int PayeeId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZipCode { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public string BillDescription { get; set; }
        public System.DateTime NextBillDate { get; set; }
        public int Intervals { get; set; }
        public int IntervalTypeId { get; set; }
        public string Payee { get; set; }
        public string PayeeEmail { get; set; }
        public int UserId { get; set; }
        public bool LateCharges { get; set; }
        public int LateChargesStartday { get; set; }
        public decimal LateChargesStartdayAmount { get; set; }
        public int LateChargesThereAfterday { get; set; }
        public decimal LateChargesThereAfterdayAmount { get; set; }
        public string CCEmail { get; set; }
        public string BCCEmail { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string EmergencyPhoneNo { get; set; }
    }
}
