//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    
    public partial class EmailedReport
    {
        public int InvoiceId { get; set; }
        public int UserId { get; set; }
        public int CustomerId { get; set; }
        public string InvoiceNumber { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmountDue { get; set; }
        public System.DateTime EmailSentDate { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string BillDescription { get; set; }
        public string CustomerEmail { get; set; }
        public bool LateCharges { get; set; }
        public int PayeeId { get; set; }
        public string Payee { get; set; }
    }
}
