//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool IsActive { get; set; }
        public string GroupDescription { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
    }
}
