//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntervalType
    {
        public IntervalType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int IntervalTypeId { get; set; }
        public string IntervalTypeDescription { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
