//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    
    public partial class InvoiceDetail
    {
        public int InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public bool IsLateCharges { get; set; }
        public decimal LateCharges { get; set; }
        public int LateChargesStartday { get; set; }
        public decimal LateChargesStartdayAmount { get; set; }
        public int LateChargesThereAfterday { get; set; }
        public decimal LateChargesThereAfterdayAmount { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public string BillDescription { get; set; }
        public string CustomerEmail { get; set; }
        public System.DateTime EmailSentDate { get; set; }
        public bool IsPaid { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmountDue { get; set; }
        public string Payee { get; set; }
        public string PayeeEmail { get; set; }
        public string CCEmail { get; set; }
        public string BCCEmail { get; set; }
    }
}
