//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.RemainderEmails = new HashSet<RemainderEmail>();
        }
    
        public int InvoiceId { get; set; }
        public int UserId { get; set; }
        public int CustomerId { get; set; }
        public string InvoiceNumber { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmountDue { get; set; }
        public System.DateTime EmailSentDate { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string BillDesc { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
        public virtual ICollection<RemainderEmail> RemainderEmails { get; set; }
    }
}
