//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineCheck
    {
        public int OnlineCheckId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string PayeeName { get; set; }
        public Nullable<decimal> AmountOnCheck { get; set; }
        public string CheckNumber { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankCity { get; set; }
        public Nullable<System.DateTime> DateOnCheck { get; set; }
        public string RoutingNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Comment { get; set; }
        public string CheckMemo { get; set; }
        public string CsvFileData { get; set; }
    }
}
