//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalAccountDetail
    {
        public int PayPalAccountId { get; set; }
        public int PayeeId { get; set; }
        public string ClientID { get; set; }
        public string ClientSecret { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int PayPalSurCharge { get; set; }
    
        public virtual Payee Payee { get; set; }
    }
}
