//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalDetail
    {
        public PayPalDetail()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int PayPalId { get; set; }
        public string PaymentResourceId { get; set; }
        public string TransactionID { get; set; }
        public decimal Amount { get; set; }
        public int UserId { get; set; }
        public System.DateTime InsertedOn { get; set; }
    
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
