//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemainderEmail
    {
        public int RemainderEmailId { get; set; }
        public int InvoiceId { get; set; }
        public System.DateTime SentDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
