//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int SubscriptionId { get; set; }
        public int UserId { get; set; }
        public int PlanId { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<System.DateTime> SubscriptionFrom { get; set; }
        public Nullable<System.DateTime> SubscriptionTo { get; set; }
    
        public virtual PaymentDetail PaymentDetail { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
