//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.CheckDetails = new HashSet<CheckDetail>();
            this.Groups = new HashSet<Group>();
            this.Invoices = new HashSet<Invoice>();
            this.Payees = new HashSet<Payee>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PayPalDetails = new HashSet<PayPalDetail>();
            this.Subscriptions = new HashSet<Subscription>();
            this.UserSecurities = new HashSet<UserSecurity>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.CustomerProfiles = new HashSet<CustomerProfile>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public bool IsInActive { get; set; }
    
        public virtual ICollection<CheckDetail> CheckDetails { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Payee> Payees { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual ICollection<PayPalDetail> PayPalDetails { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual ICollection<UserSecurity> UserSecurities { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<CustomerProfile> CustomerProfiles { get; set; }
    }
}
