//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingHousing_BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserACHBankAccount
    {
        public Nullable<int> UserId { get; set; }
        public string AccountHolderName { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public string AccountType { get; set; }
        public string AccountStatus { get; set; }
        public string BankToken { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CustomerDefaultSourceId { get; set; }
        public string CustomerId { get; set; }
    }
}
